### ISSUE TITLE
Checklist for all jekyll sites (plus some general workflow)

### ISSUE THREAD

**Issue by jamiefolsom** [hofstra/design-framework#1]
- [ ] Use PRs for all features (see process [here](https://guides.github.com/introduction/flow/)), and more specific to our use case, [here](https://github.com/scholarslab/Neatline/blob/master/github-flow.md); 
- [ ] Push feature branches to Github pages (check branch that's published) with `git push origin jf/feature-name:master` for testing, revert if it's not right.
- [ ] Add a [pull_request_template.md](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) to the repo; refer to PRs on other PSS repos to see good examples.
- [ ] Add an [issue_template.md](https://help.github.com/articles/creating-an-issue-template-for-your-repository/), with both bug and user story options; one of which would always be deleted.
- [ ] Make sure `gem github-pages` is in the `Gemfile`
- [ ] `bundle update` and confirm everything's working properly locally; deploy and retest.
- [ ] Make sure there's a README, a LICENSE in the repo, and topics, a link to the live site, and a blurb on the repo.

**Comment by feralresearch** [comment]
@jamiefolsom  

Ok I just finished doing all of these for: 
access-scholar, coyote, design-framework, drc, itinerary.

**Only repo owners can edit description, topics and link however, so part of the last item: " topics, a link to the live site, and a blurb on the repo" still needs to be done for:**

access-scholar
design-framework
itinerary

But I will merge the PRs -  I'll leave this issue open since these changes are to the repos themselves and not the files, and perhaps you want this checklist somewhere for future work.
